# EzChestShop plugin configuration
# Before starting to config, please note that any usage of TABs in the config file may break the plugin so avoid using tabs and use space.
# If you need help/found a bug, please join our Discord: https://discord.gg/rSfsqgCqBZ
language: Locale_EN
shops:
  hologram:
    # holograms are all shown in the async way and they won't waste a single tick / nor they are buggy like some other plugins
    show-holograms: true
    # represents the holographic texts of chestshops. Use %item% to display the item's display name.
    # Use [item] for 1 Line to display the floating item. Use %buy% for buy price and %sell% for sell price.
    # %currency% is defined under economy.server-currency and %owner% represents the shops creator.
    # %maxbuy% & %maxsell% can be used to define the maximum amount a player can buy/sell to a shop at this time.
    # The HTML like <buy></buy> Syntax allows the plugin to remove parts of the message if buy/sell are disabled.
    holo-structure:
      - "<custom1/>"
      - "<custom2/>"
      - "<custom3/>"
      - "<custom4/>"
      - "<buy>&fBuy: &a%buy% %currency%</buy><separator> &f| </separator><sell>&fSell: &c%sell% %currency%</sell>"
      - "&d%item%"
      - "[item]"
    holo-structure-adminshop:
      - "<custom1/>"
      - "<custom2/>"
      - "<custom3/>"
      - "<custom4/>"
      - "<buy>&fBuy: &a%buy% %currency%</buy><separator> &f| </separator><sell>&fSell: &c%sell% %currency%</sell>"
      - "&d%item%"
      - "[item]"
    # Define a custom Line spacing multiplier. 1 is default.
    holo-line-spacing: 1
    # hologram will get removed after x seconds if plugin doesn't detect any movement toward chest shop (default: 10)
    hologram-disappearance-delay: 10
    # Allows players to rotate their Holograms to be displayed on different sides of the Block.
    allow-rotation: true
    # an alternative hologram display system, which is slower but provides easier visibility of nearby shops.
    distance:
      toggled: true
      # Defines the range at which shops will render holograms (default: 10.0)
      range: 10.0
      # Set if items should be rendered first and holograms only when looking at the shop directly.
      show-items-first: false
  # Define which containers are applicable for chest shops:
  container:
    chests: true
    trapped-chests: true
    barrels: true
    shulkers: true
  display:
    # define how the plugin should format displayed numbers, use: https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/text/DecimalFormat.html
    number-format:
      gui: "###,###.##"
      chat: "###,###.##"
      hologram: "###,###.##"
  settings:
    # Define the default settings when creating a shop:
    defaults:
      transaction-message: false
      disable-buying: false
      disable-selling: false
      rotation: "up"
      share-profit: true
    # If set to true, "/ecs create 12 0" will automatically disable selling(or buying if "/ecs create 0 12")
    zero-price-equals-disabled: true
    # If set to true, this setting will require players to use a buy price that is greater than the sell price.
    buy-greater-than-sell: true
    # If set to true Shulker shops will be given some Lore when mined (Set inside the language files)
    add-shulkershop-lore: true
    # Toggle if custom amount buying or selling should be enabled.
    custom-amount-transactions: true
    hologram-messages:
      enabled: true
      # When true, custom hologram messages will be displayed even if hologram.distance.show-items-first is enabled.
      show-always: false
      # Sets how many lines can be used for custom hologram messages. If permissions.hologram-message-line-count is true, this setting is overridden.
      line-count-default: 1
economy:
  # Used to replace %currency% for the language files and the 2nd hologram line.
  server-currency: $
commands:
  # Register easier to remember alias on server startup: /shop and /adminshop
  alias:
    ecs-shop: false
    ecsadmin-adminshop: false
  checkprofit-lines-per-page: 4
permissions:
  # If set to true, players require the permission "ecs.shops.limit.X" where X is the maximum amount of shops a player can create.
  create-shops: false
  # Limit the amount of hologram messages a player can create. Use "ecs.shops.hologram.messages.limit.X"
  hologram-message-limit: false
  # Specify how many lines a player can use for their hologram messages. Use "ecs.shops.hologram.messages.lines.X"
  hologram-message-line-count: false
tasks:
  # Normally, This option is for when server(basically other plugins) remove the chest shop, in this case, it could result in some issues
  # if this is causing so much lag, you can turn this off (requires restart)
  check-for-removed-shops: true
other:
  notify-op-of-updates: true
  # When certain items are overlapping/overflowing in the gui configuration, the plugin will notify ops to take actions.
  # If you don't temper with the guis, you should never receive a notification and gui updates will happen automatically.
  notify-op-of-overlapping-gui-items: true
  notify-op-of-overflowing-gui-items: true
