name: EzChestShop
version: ${project.version}
main: me.deadlight.ezchestshop.EzChestShop
api-version: 1.14
depend: [Vault]
softdepend:
  - WildChests
  - WorldGuard
  - Slimefun #in case just to load after the Slimefun
  - Multiverse-Core #preventing null worlds
  - CMI
authors: [Dead_Light, ElitoGame]
description: ${project.description}
commands:
  ecs:
    description: create or delete a shop
    aliases:
      - cs
      - cshop
      - chestshop
      - ezchestshop
  ecsadmin:
    description: commands designed for admins to moderate
  checkprofits:
    description: Check all your shop profits that you made offline!
    aliases:
      - cp
